name: pipeline_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pymongo=4.8.0
  - requests=2.32.3
  - tqdm=4.66.5
  - beautifulsoup4=4.12.2
  - lxml=4.9.3
  - matplotlib=3.9.2
  - ipykernel=6.19.2
